[package]
name = "note_app_backend"
version = "0.1.0"
authors = ["joss1998 <jocelyne.jamilet1998@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
